apiVersion: apps/v1
kind: Deployment
metadata:
  name: webaccess-deployment
  labels:
    app: webaccess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webaccess
  template:
    metadata:
      labels:
        app: webaccess
    spec:
      containers:
      - name: webaccess-container
        image: localhost:5000/webaccess
        ports:
        - containerPort: 9080
        env:
          - name: PERSONEN_SERVICE_ROOT_URL
            value: "http://freedb-service:8080"
      nodeSelector:
        nodetype: agent

---

apiVersion: v1
kind: Service
metadata:
  name: webaccess-service
spec:
  type: NodePort
  selector:
    app: webaccess
  ports:
  - name: webaccess-http
    protocol: TCP
    nodePort: 30080
    port: 9080
    targetPort: 9080
